version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.15.1-browsers-legacy

    working_directory: ~/we-vue

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-packages-{{ .Branch }}-

      - run: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # test packages/we-vue
      - run: yarn test:coverage

      # update codecov stats
      - run: yarn lerna run coverage --scope we-vue

      # build component lib and dist
      - run: yarn lerna run build --scope we-vue

      # build demo and docs
      - run: yarn lerna run build --ignore we-vue

      - persist_to_workspace:
          root: ./
          paths:
            - packages/demo/dist
            - packages/docs/dist

  deploy:
    docker:
      - image: circleci/node:10.15.1-browsers-legacy

    steps:
      - attach_workspace:
          at: ~/we-vue

      - add_ssh_keys:
          fingerprints:
            - "6a:aa:77:77:28:51:9f:01:4b:b2:7e:3e:ea:f6:20:1a"

      - run: echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - run: sudo apt install rsync -y

      # deploy demo
      - deploy:
          name: deploy demo
          when: on_success
          command: |
            rsync -vzrtopg --progress -e ssh --delete ~/we-vue/packages/demo/dist/* $DEPLOY_USER@$DEPLOY_HOST:/data/wwwroot/demo.wevue.org

      # deploy docs
      - deploy:
          name: deploy docs
          when: on_success
          command: |
            rsync -vzrtopg --progress -e ssh --delete ~/we-vue/packages/docs/dist/* $DEPLOY_USER@$DEPLOY_HOST:/data/wwwroot/wevue.org

workflows:
  version: 2
  # deploy both demo and docs-site
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - docs
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - docs
