version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.15.1-browsers-legacy

    working_directory: ~/we-vue

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lcok" }}
          # fallback to using the latest cache if no exact match is found
          - yarn-packages-{{ .Branch }}-

      - run: yarn --frozen-lockfile --non-interactive

      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lcok" }}
          paths:
            - ~/.cache/yarn

      # test packages/we-vue
      - run: yarn test:coverage

      # update codecov stats TODO
      #- run: ./node_modules/.bin/codecov

      # build demo
      - run: yarn lerna run build --scope demo

      # build docs
      - run: yarn lerna run build --scope docs

      - persist_to_workspace:
          root: ./
          paths:
            - packages/demo/dist
            - packages/docs/dist

  deploy:
    docker:
      - image: circleci/node:10.15.1-browsers-legacy

    steps:
      - attach_workspace:
          at: ~/we-vue

      - add_ssh_keys:
          fingerprints:
            - "6f:b8:91:11:81:42:a3:9c:24:17:cf:be:e9:0b:41:67"

      - run: echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      # deploy demo
      - deploy:
          name: deploy demo
          when: on_success
          command: |
            rsync -vzrtopg --progress -e ssh --delete ~/we-vue/packages/demo/dist/* $DEPLOY_USER@$DEPLOY_HOST:/data/wwwroot/demo.wevue.org

      # deploy docs
      - deploy:
          name: deploy docs
          when: on_success
          command: |
            rsync -vzrtopg --progress -e ssh --delete ~/we-vue/packages/docs/dist/* $DEPLOY_USER@$DEPLOY_HOST:/data/wwwroot/wevue.org

workflows:
  version: 2
  # deploy both demo and docs-site
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - docs
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - docs
